package model;
// Generated Oct 7, 2021 7:16:23 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cita generated by hbm2java
 */
@Entity
@Table(name="cita"
    ,catalog="dbclinica"
)
public class Cita  implements java.io.Serializable {


     private int idCita;
     private Usuario usuarioByIdUsuario;
     private Usuario usuarioByIdDoctor;
     private Usuario usuarioByIdPaciente;
     private String titulo;
     private Date fechaCita;
     private int idEstado;

    public Cita() {
    }

    public Cita(int idCita, Usuario usuarioByIdUsuario, Usuario usuarioByIdDoctor, Usuario usuarioByIdPaciente, String titulo, Date fechaCita, int idEstado) {
       this.idCita = idCita;
       this.usuarioByIdUsuario = usuarioByIdUsuario;
       this.usuarioByIdDoctor = usuarioByIdDoctor;
       this.usuarioByIdPaciente = usuarioByIdPaciente;
       this.titulo = titulo;
       this.fechaCita = fechaCita;
       this.idEstado = idEstado;
    }
   
     @Id 

    
    @Column(name="idCita", unique=true, nullable=false)
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario", nullable=false)
    public Usuario getUsuarioByIdUsuario() {
        return this.usuarioByIdUsuario;
    }
    
    public void setUsuarioByIdUsuario(Usuario usuarioByIdUsuario) {
        this.usuarioByIdUsuario = usuarioByIdUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDoctor", nullable=false)
    public Usuario getUsuarioByIdDoctor() {
        return this.usuarioByIdDoctor;
    }
    
    public void setUsuarioByIdDoctor(Usuario usuarioByIdDoctor) {
        this.usuarioByIdDoctor = usuarioByIdDoctor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPaciente", nullable=false)
    public Usuario getUsuarioByIdPaciente() {
        return this.usuarioByIdPaciente;
    }
    
    public void setUsuarioByIdPaciente(Usuario usuarioByIdPaciente) {
        this.usuarioByIdPaciente = usuarioByIdPaciente;
    }

    
    @Column(name="titulo", nullable=false, length=50)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaCita", nullable=false, length=19)
    public Date getFechaCita() {
        return this.fechaCita;
    }
    
    public void setFechaCita(Date fechaCita) {
        this.fechaCita = fechaCita;
    }

    
    @Column(name="idEstado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }




}


