package model;
// Generated Oct 7, 2021 7:16:23 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstadocitaId generated by hbm2java
 */
@Embeddable
public class EstadocitaId  implements java.io.Serializable {


     private int idEstado;
     private String estado;

    public EstadocitaId() {
    }

    public EstadocitaId(int idEstado, String estado) {
       this.idEstado = idEstado;
       this.estado = estado;
    }
   


    @Column(name="idEstado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }


    @Column(name="estado", nullable=false, length=25)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstadocitaId) ) return false;
		 EstadocitaId castOther = ( EstadocitaId ) other; 
         
		 return (this.getIdEstado()==castOther.getIdEstado())
 && ( (this.getEstado()==castOther.getEstado()) || ( this.getEstado()!=null && castOther.getEstado()!=null && this.getEstado().equals(castOther.getEstado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEstado();
         result = 37 * result + ( getEstado() == null ? 0 : this.getEstado().hashCode() );
         return result;
   }   


}


