package model;
// Generated Oct 7, 2021 7:16:23 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Estadocita generated by hbm2java
 */
@Entity
@Table(name="estadocita"
    ,catalog="dbclinica"
)
public class Estadocita  implements java.io.Serializable {


     private EstadocitaId id;

    public Estadocita() {
    }

    public Estadocita(EstadocitaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEstado", column=@Column(name="idEstado", nullable=false) ), 
        @AttributeOverride(name="estado", column=@Column(name="estado", nullable=false, length=25) ) } )
    public EstadocitaId getId() {
        return this.id;
    }
    
    public void setId(EstadocitaId id) {
        this.id = id;
    }




}


