package model;
// Generated Oct 7, 2021 7:16:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Expedientepaciente generated by hbm2java
 */
@Entity
@Table(name="expedientepaciente"
    ,catalog="dbclinica"
)
public class Expedientepaciente  implements java.io.Serializable {


     private int idExpediente;
     private Usuario usuarioByIdPaciente;
     private Usuario usuarioByIdDoctor;
     private String titulo;
     private Set<Seguimientopaciente> seguimientopacientes = new HashSet<Seguimientopaciente>(0);

    public Expedientepaciente() {
    }

	
    public Expedientepaciente(int idExpediente, Usuario usuarioByIdPaciente, Usuario usuarioByIdDoctor, String titulo) {
        this.idExpediente = idExpediente;
        this.usuarioByIdPaciente = usuarioByIdPaciente;
        this.usuarioByIdDoctor = usuarioByIdDoctor;
        this.titulo = titulo;
    }
    public Expedientepaciente(int idExpediente, Usuario usuarioByIdPaciente, Usuario usuarioByIdDoctor, String titulo, Set<Seguimientopaciente> seguimientopacientes) {
       this.idExpediente = idExpediente;
       this.usuarioByIdPaciente = usuarioByIdPaciente;
       this.usuarioByIdDoctor = usuarioByIdDoctor;
       this.titulo = titulo;
       this.seguimientopacientes = seguimientopacientes;
    }
   
     @Id 

    
    @Column(name="idExpediente", unique=true, nullable=false)
    public int getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(int idExpediente) {
        this.idExpediente = idExpediente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPaciente", nullable=false)
    public Usuario getUsuarioByIdPaciente() {
        return this.usuarioByIdPaciente;
    }
    
    public void setUsuarioByIdPaciente(Usuario usuarioByIdPaciente) {
        this.usuarioByIdPaciente = usuarioByIdPaciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDoctor", nullable=false)
    public Usuario getUsuarioByIdDoctor() {
        return this.usuarioByIdDoctor;
    }
    
    public void setUsuarioByIdDoctor(Usuario usuarioByIdDoctor) {
        this.usuarioByIdDoctor = usuarioByIdDoctor;
    }

    
    @Column(name="titulo", nullable=false, length=50)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="expedientepaciente")
    public Set<Seguimientopaciente> getSeguimientopacientes() {
        return this.seguimientopacientes;
    }
    
    public void setSeguimientopacientes(Set<Seguimientopaciente> seguimientopacientes) {
        this.seguimientopacientes = seguimientopacientes;
    }




}


