package model;
// Generated Oct 7, 2021 7:16:23 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="dbclinica"
)
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private String nombre;
     private String apellido;
     private int edad;
     private String correo;
     private String direccion;
     private String departamento;
     private int habilitado;
     private Date fechaNacimiento;

    public Persona() {
    }

    public Persona(String nombre, String apellido, int edad, String correo, String direccion, String departamento, int habilitado, Date fechaNacimiento) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.correo = correo;
       this.direccion = direccion;
       this.departamento = departamento;
       this.habilitado = habilitado;
       this.fechaNacimiento = fechaNacimiento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPersona", unique=true, nullable=false)
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=30)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="edad", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }

    
    @Column(name="correo", nullable=false, length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="direccion", nullable=false, length=30)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="departamento", nullable=false, length=30)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="habilitado", nullable=false)
    public int getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(int habilitado) {
        this.habilitado = habilitado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }




}


