package model;
// Generated Oct 7, 2021 7:16:23 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="dbclinica"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private int idPersona;
     private int idTipoUsuario;
     private String usuario;
     private String clave;
     private String habilitado;
     private Date fechaUsaurio;
     private Set<Expedientepaciente> expedientepacientesForIdPaciente = new HashSet<Expedientepaciente>(0);
     private Set<Cita> citasForIdUsuario = new HashSet<Cita>(0);
     private Set<Expedientepaciente> expedientepacientesForIdDoctor = new HashSet<Expedientepaciente>(0);
     private Set<Cita> citasForIdDoctor = new HashSet<Cita>(0);
     private Set<Cita> citasForIdPaciente = new HashSet<Cita>(0);

    public Usuario() {
    }

	
    public Usuario(int idPersona, int idTipoUsuario, String usuario, String clave, String habilitado, Date fechaUsaurio) {
        this.idPersona = idPersona;
        this.idTipoUsuario = idTipoUsuario;
        this.usuario = usuario;
        this.clave = clave;
        this.habilitado = habilitado;
        this.fechaUsaurio = fechaUsaurio;
    }
    public Usuario(int idPersona, int idTipoUsuario, String usuario, String clave, String habilitado, Date fechaUsaurio, Set<Expedientepaciente> expedientepacientesForIdPaciente, Set<Cita> citasForIdUsuario, Set<Expedientepaciente> expedientepacientesForIdDoctor, Set<Cita> citasForIdDoctor, Set<Cita> citasForIdPaciente) {
       this.idPersona = idPersona;
       this.idTipoUsuario = idTipoUsuario;
       this.usuario = usuario;
       this.clave = clave;
       this.habilitado = habilitado;
       this.fechaUsaurio = fechaUsaurio;
       this.expedientepacientesForIdPaciente = expedientepacientesForIdPaciente;
       this.citasForIdUsuario = citasForIdUsuario;
       this.expedientepacientesForIdDoctor = expedientepacientesForIdDoctor;
       this.citasForIdDoctor = citasForIdDoctor;
       this.citasForIdPaciente = citasForIdPaciente;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUsuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="idPersona", nullable=false)
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

    
    @Column(name="idTipoUsuario", nullable=false)
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }

    
    @Column(name="usuario", nullable=false, length=15)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="clave", nullable=false, length=15)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="habilitado", nullable=false, length=1)
    public String getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(String habilitado) {
        this.habilitado = habilitado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_usaurio", nullable=false, length=19)
    public Date getFechaUsaurio() {
        return this.fechaUsaurio;
    }
    
    public void setFechaUsaurio(Date fechaUsaurio) {
        this.fechaUsaurio = fechaUsaurio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarioByIdPaciente")
    public Set<Expedientepaciente> getExpedientepacientesForIdPaciente() {
        return this.expedientepacientesForIdPaciente;
    }
    
    public void setExpedientepacientesForIdPaciente(Set<Expedientepaciente> expedientepacientesForIdPaciente) {
        this.expedientepacientesForIdPaciente = expedientepacientesForIdPaciente;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarioByIdUsuario")
    public Set<Cita> getCitasForIdUsuario() {
        return this.citasForIdUsuario;
    }
    
    public void setCitasForIdUsuario(Set<Cita> citasForIdUsuario) {
        this.citasForIdUsuario = citasForIdUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarioByIdDoctor")
    public Set<Expedientepaciente> getExpedientepacientesForIdDoctor() {
        return this.expedientepacientesForIdDoctor;
    }
    
    public void setExpedientepacientesForIdDoctor(Set<Expedientepaciente> expedientepacientesForIdDoctor) {
        this.expedientepacientesForIdDoctor = expedientepacientesForIdDoctor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarioByIdDoctor")
    public Set<Cita> getCitasForIdDoctor() {
        return this.citasForIdDoctor;
    }
    
    public void setCitasForIdDoctor(Set<Cita> citasForIdDoctor) {
        this.citasForIdDoctor = citasForIdDoctor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarioByIdPaciente")
    public Set<Cita> getCitasForIdPaciente() {
        return this.citasForIdPaciente;
    }
    
    public void setCitasForIdPaciente(Set<Cita> citasForIdPaciente) {
        this.citasForIdPaciente = citasForIdPaciente;
    }




}


